import os
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
import uvicorn
import base64
from io import BytesIO
import requests
import replicate

# --- App Setup ---
app = FastAPI()

# --- Replicate API Setup ---
replicate_token = os.getenv("REPLICATE_API_TOKEN")
if not replicate_token:
    print("⚠️  REPLICATE_API_TOKEN not set. Logo generation will use mock data.")
    print("Get a free token at: https://replicate.com/account/api-tokens")
    replicate_token = None
else:
    print("✅ Replicate API token initialized")

# --- API Request Model ---
class ImageRequest(BaseModel):
    prompt: str

# --- Endpoints ---

@app.post("/api/generate-image")
async def generate_image(req: ImageRequest):
    """Generate an image using Replicate's Flux model"""
    
    if not replicate_token:
        raise HTTPException(
            status_code=500, 
            detail="REPLICATE_API_TOKEN not set. Get a free token at https://replicate.com/account/api-tokens"
        )
    
    try:
        print(f"🎨 Generating logo: {req.prompt}")
        
        # Call Replicate API using Flux model
        output = replicate.run(
            "black-forest-labs/flux-schnell",
            input={
                "prompt": req.prompt,
                "steps": 4,
                "guidance": 0
            },
            api_token=replicate_token
        )
        
        # output is a list of image URLs
        if output and len(output) > 0:
            image_url = output[0]
            
            # Download the image and convert to base64
            response = requests.get(image_url)
            img_data = response.content
            img_str = base64.b64encode(img_data).decode("utf-8")
            
            return {"url": f"data:image/png;base64,{img_str}"}
        else:
            raise Exception("No image generated by Replicate")
            
    except Exception as e:
        print(f"Error during generation: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# --- Static Files (Serve Frontend) ---
# Serve the current directory's static files (css, js)
app.mount("/", StaticFiles(directory=".", html=True), name="static")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
